default: &default
  adapter: postgresql
  username: postgres
  encoding: unicode
  pool: 5
  host: db

development:
  <<: *default
  database: divaa_development

test:
  <<: *default
  database: divaa_test

production:
  <<: *default
  database: divaa_production
  username: <%= ENV["RAILS_DB_USER"] %>
  password: <%= ENV["RAILS_DB_PASSWORD"] %>
